### ISSUE TITLE
Provide better introduction and documentation

### ISSUE THREAD

**Issue by OldhamMade** [getcodelimit/codelimit#18]
It is a little unclear what CodeLimit does, and what it deems to be an issue. Please provide more of a description and breakdown of features and benefits.

**Comment by OldhamMade** [comment]
Thanks @robvanderleek. One thing that would be useful to cover is how this project is different to tools that calculate cyclomatic complexity such as Radon/McCabe/Lizard.

**Comment by robvanderleek** [comment]
Short update on this issue:
I've worked on documentation in the [README](https://github.com/getcodelimit/codelimit) and also created a [separate documentation site](https://codelimit-docs.vercel.app/).
Far from done but interested in any intermediate feedback 🙂

**Comment by robvanderleek** [comment]
Another update:
I've moved most of the documentation from the README to https://codelimit-docs.vercel.app/
