### ISSUE TITLE
support a "nocl" comment that ignores particular functions

### ISSUE THREAD

**Issue by bbelderbos** [getcodelimit/codelimit#20]
With Flake8 you can add `# noqa` to ignore violations for specific lines. This could be useful here as well when you don't want to include certain functions in the codelimit report (for whatever reason). 

Suggestion: `def my_long_function(...)  # nocl` 

nocl = "no code limit"

**Comment by robvanderleek** [comment]
Hi @bbelderbos 👋 

This option is in `main` now 🚀 

Please see the [documentation](https://codelimit-docs.vercel.app/configuration/) for some examples of how to use it.

Thanks for suggesting this feature!

**Comment by bbelderbos** [comment]
That's awesome @robvanderleek, thanks!
