### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by chenrui333** [getcodelimit/codelimit#26]
looks like currently, the build not support python 3.12

https://github.com/getcodelimit/codelimit/blob/55d40afb250ecd704b9f2755afa02f06925314dd/pyproject.toml#L12

relates to https://github.com/Homebrew/homebrew-core/pull/151028

**Comment by chenrui333** [comment]
> Is homebrew defaulting to Python 3.12? (in other words, is this an urgent issue?)

we planneed to :) 



> I tried running Code Limit with Python 3.12 but bumped into [an issue installing a transitive dependency (aiohttp)](https://github.com/getcodelimit/codelimit/actions/runs/6539219150/job/17756837114?pr=27).

you can try out `3.9.0b0` release

this is related to https://github.com/aio-libs/aiohttp/issues/7675

**Comment by chenrui333** [comment]
with that being said, it is not urgent, we will still have python3.11 support as well as other python releases

**Comment by chenrui333** [comment]
@robvanderleek heads up, aiohttp just made a 3.9.0 release over the weekend. 🚀

**Comment by robvanderleek** [comment]
Hey @chenrui333 

Thanks for the notification!
I've just merged Python 3.12 support to `main`.

Appreciate all the support,
Rob
